"""Generate a PDF findings report from a pipeline result (reportlab)."""
import io
from datetime import datetime


def build_pdf(result: dict) -> bytes:
    """Return PDF bytes for a scan result dict (from run_full_scan / _LATEST)."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                    TableStyle)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm,
                            leftMargin=2 * cm, rightMargin=2 * cm,
                            title=f"ArgusPredict report - {result.get('target')}")
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=colors.HexColor("#726DA8"))
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8,
                           textColor=colors.HexColor("#555555"))
    story = []

    story.append(Paragraph("ArgusPredict &mdash; Attack Surface Report", h1))
    story.append(Paragraph(f"Target: <b>{result.get('target')}</b>", styles["Normal"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", small))
    story.append(Spacer(1, 0.4 * cm))

    s = result.get("summary", {})
    summ = [["Assets", s.get("assets", 0)], ["Open ports", s.get("open_ports", 0)],
            ["Changes", s.get("changes", 0)], ["Anomalies", s.get("anomalies", 0)],
            ["Top risk", s.get("top_risk", 0)], ["Scan (s)", s.get("duration_seconds", 0)]]
    t = Table([["Metric", "Value"]] + summ, colWidths=[6 * cm, 4 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2421")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#DCE1DE")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Prioritised risks (context-aware)", styles["Heading2"]))
    rows = [["Risk", "Node", "Service", "Base CVSS", "Anomaly"]]
    for r in result.get("risk_report", [])[:25]:
        rows.append([r["composite_risk"], r["node"], r.get("service", ""),
                     r["cvss_base"], r.get("anomaly_score", 0)])
    rt = Table(rows, colWidths=[2 * cm, 5 * cm, 3 * cm, 2.5 * cm, 2.5 * cm])
    style = [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#726DA8")),
             ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
             ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
             ("FONTSIZE", (0, 0), (-1, -1), 8)]
    for i, r in enumerate(result.get("risk_report", [])[:25], start=1):
        v = r["composite_risk"]
        c = "#70161E" if v >= 9 else "#C97B4A" if v >= 7 else "#ECCE8E" if v >= 4 else "#8FB0A0"
        style.append(("BACKGROUND", (0, i), (0, i), colors.HexColor(c)))
    rt.setStyle(TableStyle(style))
    story.append(rt)
    story.append(Spacer(1, 0.5 * cm))

    changes = result.get("changes", [])
    story.append(Paragraph(f"Changes detected ({len(changes)})", styles["Heading2"]))
    if changes:
        for c in changes[:40]:
            story.append(Paragraph(f"[{c['event_type']}] {c['detail']}", small))
    else:
        story.append(Paragraph("No changes since the previous scan.", small))

    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph("Authorised, observational reconnaissance only. "
                           "Generated by ArgusPredict.", small))

    doc.build(story)
    return buf.getvalue()